services:
  # Full Stack App (Frontend + Backend)
  app:
    build: .
    ports:
      - "3000:3000" # Frontend
      - "6060:6060" # Backend API
    env_file:
      - .env
    environment:
      # Override only Docker-specific values
      - S3_ENDPOINT=minio:9000
      - S3_USE_SSL=false
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin
      - S3_FORCE_PATH_STYLE=true
      - DB_SSLMODE=disable
      # Frontend environment
      - NEXT_PUBLIC_DEV_SERVER_URL=http://localhost:6060/api/v1
    depends_on:
      - minio

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # PostgreSQL (if you need a database)
  # postgres:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_DB=oss-archive
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  minio_data:
  # postgres_data:
