services:
  # MinIO for local S3 storage
  minio:
    image: minio/minio
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Create MinIO bucket (one-shot job)
  minio-setup:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      echo 'Setting up MinIO bucket...';
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      if ! /usr/bin/mc ls myminio/oss-archive >/dev/null 2>&1; then
        echo 'Creating bucket oss-archive...';
        /usr/bin/mc mb myminio/oss-archive;
        /usr/bin/mc anonymous set public myminio/oss-archive;
        echo 'Bucket created successfully';
      else
        echo 'Bucket oss-archive already exists, skipping creation';
      fi;
      exit 0;
      "

  # Frontend in development mode with hot reload
  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=/api/v1
      - BACKEND_URL=http://host.docker.internal:6060
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    depends_on:
      - minio

volumes:
  minio_data:
