version: "3.8"

services:
  # Go Backend
  api:
    build: .
    ports:
      - "6060:6060"
    depends_on:
      - minio
      - postgres
    volumes:
      - ./configs:/app/configs

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # PostgreSQL (if you need a database)
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=oss-archive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  minio_data:
  postgres_data:
