# Database configuration

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: oss-archive
  sslmode: disable

server:
  port: 6060
  read_timeout: 30 # seconds - max time to read request
  write_timeout: 30 # seconds - max time to write response
  idle_timeout: 120 # seconds - max idle connection time
  shutdown_timeout: 5 # seconds - graceful shutdown timeout

logging:
  level: info # debug, info, warn, error
  mode: release # debug, release, test

s3:
  endpoint: localhost:9000 # For MinIO, leave empty for AWS S3
  region: us-east-1 
  access_key_id: minioadmin 
  secret_access_key: minioadmin 
  use_ssl: false 
  bucket_name: files
  force_path_style: true # true for MinIO, false for AWS S3
